language: julia
os:
  - osx
julia:
  - 1.6
branches:
    only:
    - main
notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.6
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/cvdlab/LinearAlgebraicRepresentation.jl")); Pkg.instantiate();  Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
