language: julia
os:
  - linux
julia:
  - 1.6
branches:
    only:
    - main
notifications:
  email: false

# jobs:
#   include:
#     - stage: "Documentation"
#     julia: 1.6
#     os: osx
#     script:
#       - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();'
#       - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter")'
#       - julia --project=docs/ docs/make.jl
#       after_success: skip
